# Reflex Diagnostic Configuration

reflex_verbosity: high        # Options: low, medium, high
include_divergence_delta: true    # Export pre/post divergence per cell
include_pressure_mutation_map: true    # Log pressure delta per cell
log_projection_trace: true     # Enable solver mutation diagnostics
ghost_adjacency_depth: 1       # Influence tagging radius (default = 1)
include_mutation_pathways: true   # Enable mutation causality tracing
export_influence_flags: true      # Enable ghost influence map export
enable_reflex_snapshot_overlay: false  # Optional: visualize mutation overlap per step



